In [2]:
def celsius_fahrenheit () :
    # F = (c * 9/5) + 32
    fahrenheit = (22 * (9 / 5)) + 32
    print(fahrenheit)
    return fahrenheit

def command is used to define a new function. the syntax is that we have to use a colon to finish this command. hitting enter introduces an indent. otherwise there could be syntax error.here fehrenheit in 3rd line is a variable.the 2nd line is the formula of fehrenheit to celsius. in the 3rd line we give it what celsius to convert into fehrenheit. now after shift+enter the cell is executed but to see this we call this by the following command-

In [3]:
celsius_fahrenheit()

71.6

71.6

the first output is from the print command, the second command is from the return. the arguments are stored within the function as variables.

In [4]:
def celsius_fahrenheit (C) :
    # F = (c * 9/5) + 32
    fahrenheit = (C * (9 / 5)) + 32
    print(fahrenheit)
    return fahrenheit

instead of putting () without argument we canput a C here to convert any C to fahrenheit. we need to change at 2 points- put a c in the brackets of arguments and put a C in the variable part.

In [5]:
celsius_fahrenheit(100)

212.0

212.0

In [6]:
celsius_fahrenheit(C)

NameError: name 'C' is not defined

In [10]:
def fahrenheit_celsius(F):
    # C = (F - 32) * (5 / 9)
    celsius = (F - 32) * (5 / 9)
    print(celsius)
    return celsius

In [11]:
fahrenheit_celsius(35)

1.6666666666666667

1.6666666666666667

whole thing in the cell is the function

In [18]:
import pandas as pd

what does import pandas do? help read a data.

In [19]:
dem_health_data = pd.read_csv("Dem_Health_Full.txt", sep="\t" )

"\t" is for the tab seperated values. sep is an argument for a seperator in this case which is a tab. our file is a comma seperated values that we are overwriting as a tab separated values.

In [22]:
dem_health_data.head(20)

,County,State,Population_Density,Poverty,Infant_Mortality,Suicide,Total_Births,Total_Deaths
0,Autauga,AL,82,10.4,5.9,16.6,3048.0,1867.0
1,Baldwin,AL,102,10.2,7.1,14.3,5471.0,4388.0
2,Barbour,AL,32,22.1,7.1,10.3,1835.0,1538.0
3,Bibb,AL,35,16.8,9.8,14.8,2801.0,2012.0
4,Blount,AL,86,11.9,9.0,14.4,3318.0,2453.0
5,Bullock,AL,18,26.2,13.3,-1111.1,1604.0,1381.0
6,Butler,AL,27,20.0,5.8,11.9,2874.0,2857.0
7,Calhoun,AL,184,16.4,9.5,13.6,4429.0,3915.0
8,Chambers,AL,59,16.2,7.5,12.8,2271.0,2424.0
9,Cherokee,AL,44,15.2,7.4,17.7,2659.0,2609.0
10,Chilton,AL,60,14.9,10.5,13.3,2671.0,2065.0
11,Choctaw,AL,16,18.7,10.8,9.4,2152.0,1742.0
12,Clarke,AL,22,19.2,7.1,8.9,1984.0,1444.0
13,Clay,AL,23,14.0,10.2,11.2,1748.0,1706.0
14,Cleburne,AL,26,14.0,7.0,30.1,1706.0,1540.0
15,Coffee,AL,67,13.7,2.9,13.1,2762.0,2210.0
16,Colbert,AL,92,14.0,8.2,15.1,3166.0,3087.0
17,Conecuh,AL,16,22.0,14.4,13.2,1872.0,1832.0
18,Coosa,AL,17,13.4,13.9,-1111.1,1273.0,1174.0
19,Covington,AL,36,17.5,6.2,10.7,2247.0,2499.0

In [25]:
def get_urban(df):
    urban = df.loc[df['Population_Density'] >= 1000, :]
    return urban

whatever is in under loc is in 3rd brackets, it is a conditional arg in the brackets, in this case how may rows you wanna keep how many columns you wanna keep [row, column]. df means it is going to the pandas library. it is a pandas object so it understands that i want some function from pandas library. df is the data frame it is keeping rows of the column pop density that are eq or greater than 1000

In [27]:
urban_counties = get_urban(dem_health_data)

In [28]:
urban_counties

,County,State,Population_Density,Poverty,Infant_Mortality,Suicide,Total_Births,Total_Deaths
184,Alameda,CA,1964,10.7,4.8,7.6,65423.0,29143.0
190,Contra Costa,CA,1414,7.5,4.0,9.4,39653.0,20836.0
202,Los Angeles,CA,2447,17.7,5.4,7.9,457033.0,181018.0
213,Orange,CA,3785,10.6,4.7,7.6,135702.0,51060.0
217,Sacramento,CA,1412,13.7,5.6,10.9,58592.0,28774.0
221,San Francisco,CA,15837,12.0,3.9,11.0,25255.0,18969.0
224,San Mateo,CA,1558,6.8,4.1,7.1,30483.0,14256.0
226,Santa Clara,CA,1316,8.8,4.0,7.6,81257.0,26130.0
258,Denver,CO,3638,15.1,6.7,14.2,34354.0,13530.0
306,Fairfield,CT,1443,7.3,5.3,6.3,36336.0,21011.0
307,Hartford,CT,1193,9.2,6.3,7.6,31212.0,23682.0
310,New Haven,CT,1398,9.4,6.8,7.6,30738.0,23078.0
315,New Castle,DE,1227,8.2,9.4,11.1,21109.0,12346.0
317,Washington,DC,8966,17.5,10.9,6.0,22742.0,17375.0
323,Broward,FL,1475,12.5,6.5,13.3,67007.0,48248.0
332,Duval,FL,1068,12.8,10.3,14.5,36661.0,20511.0
345,Hillsborough,FL,1077,13.0,8.7,12.6,45253.0,26268.0
360,Miami-Dade,FL,1221,18.9,5.9,9.1,97091.0,55624.0
365,Orange,FL,1127,13.2,7.5,9.9,43304.0,19432.0
369,Pinellas,FL,3315,12.1,7.6,16.3,27592.0,37641.0
376,Seminole,FL,1303,9.1,5.5,13.0,13633.0,8050.0
415,Clayton,GA,1879,13.9,10.2,11.5,13391.0,4067.0
417,Cobb,GA,1952,9.6,6.4,9.2,31600.0,9967.0
428,DeKalb,GA,2528,13.2,9.2,9.7,32375.0,11887.0
444,Fulton,GA,1732,16.2,8.7,8.7,40860.0,18471.0
451,Gwinnett,GA,1678,8.2,6.5,9.6,34815.0,8012.0
545,Honolulu,HI,1509,10.5,7.3,9.5,38506.0,18565.0
608,Cook,IL,5608,14.5,8.5,7.5,247949.0,134307.0
614,DuPage,IL,2785,5.9,6.6,7.3,39133.0,17092.0
641,Lake,IL,1570,6.9,5.0,7.6,31544.0,11514.0
...,...,...,...,...,...,...,...,...
2917,Charlottesville City,VA,3941,17.8,7.4,11.6,2553.0,1737.0
2919,Colonial Heights City,VA,2349,7.4,6.7,13.8,2847.0,2044.0
2920,Covington City,VA,1094,12.7,6.6,-1111.1,834.0,1031.0
2921,Danville City,VA,1072,19.3,10.1,19.3,2861.0,3768.0
2923,Fairfax City,VA,3481,5.5,6.7,13.2,3271.0,2080.0
2924,Falls Church City,VA,5418,3.0,5.4,9.4,1866.0,790.0
2925,Franklin City,VA,1029,17.3,9.8,11.3,1154.0,1332.0
2926,Fredericksburg City,VA,1971,14.1,9.1,15.1,3936.0,2179.0
2928,Hampton City,VA,2811,13.1,11.6,8.5,5611.0,3410.0
2929,Harrisonburg City,VA,2303,17.9,5.9,10.4,2382.0,1298.0
2930,Hopewell City,VA,2216,16.4,10.5,14.4,3525.0,2654.0
2931,Lexington City,VA,2721,16.1,NaN,-1111.1,558.0,767.0
2932,Lynchburg City,VA,1356,17.5,9.2,11.0,4221.0,4057.0
2933,Manassas City,VA,3783,7.5,4.5,-1111.1,3593.0,959.0
2934,Manassas Park City,VA,4667,6.5,6.3,-1111.1,1915.0,347.0
2935,Martinsville City,VA,1362,17.9,2.4,19.9,1907.0,2598.0
2936,Newport News City,VA,2634,14.0,11.7,10.1,9587.0,4220.0
2937,Norfolk City,VA,4317,19.8,11.0,12.6,12143.0,6226.0
2939,Petersburg City,VA,1425,18.5,12.6,9.1,2706.0,2471.0
2941,Portsmouth City,VA,3021,16.5,14.2,13.4,4726.0,3254.0
2942,Radford City,VA,1484,18.5,6.8,19.1,1317.0,1023.0
2943,Richmond City,VA,3226,20.2,14.8,11.5,9287.0,6989.0
2944,Roanoke City,VA,2160,16.9,10.5,16.1,6456.0,6277.0
2945,Salem City,VA,1690,8.4,7.6,11.2,2528.0,3045.0
2946,Staunton City,VA,1184,13.1,6.6,14.5,2527.0,2964.0
2948,Virginia Beach City,VA,1766,8.0,7.1,9.8,18786.0,7655.0
2949,Waynesboro City,VA,1385,13.1,8.1,19.7,2731.0,2330.0
2950,Williamsburg City,VA,1376,17.5,11.2,16.4,1192.0,1288.0
2951,Winchester City,VA,2692,12.0,8.0,15.8,3336.0,2628.0
3086,Milwaukee,WI,3815,16.2,10.4,11.4,43885.0,26557.0

In [32]:
def get_urban(df, threshold):
    urban = df.loc[df['Population_Density'] >= 500, :]
    return urban

In [33]:
urban_counties = get_urban(dem_health_data, 500)

In [34]:
urban_counties.head()

,County,State,Population_Density,Poverty,Infant_Mortality,Suicide,Total_Births,Total_Deaths
36,Jefferson,AL,591,14.4,11.3,11.3,27118.0,21937.0
184,Alameda,CA,1964,10.7,4.8,7.6,65423.0,29143.0
190,Contra Costa,CA,1414,7.5,4.0,9.4,39653.0,20836.0
202,Los Angeles,CA,2447,17.7,5.4,7.9,457033.0,181018.0
213,Orange,CA,3785,10.6,4.7,7.6,135702.0,51060.0

In [72]:
def split_county_by_pop(df, threshold):
    urban = df.loc[df['Population_Density'] >= threshold, :]
    rural = df.loc[df['Population_Density'] < threshold, :]
    return [urban, rural]

In [73]:
urban_rural_counties = split_county_by_pop(dem_health_data, 500)